# Generated by Django 6.0.2 on 2026-03-30 07:54

import django.core.validators
import multiselectfield.db.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='artikul_ky',
        ),
        migrations.RemoveField(
            model_name='books',
            name='artikul_ru',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_ky',
        ),
        migrations.RemoveField(
            model_name='books',
            name='author_ru',
        ),
        migrations.RemoveField(
            model_name='books',
            name='razdel',
        ),
        migrations.RemoveField(
            model_name='books',
            name='razdel_ky',
        ),
        migrations.RemoveField(
            model_name='books',
            name='razdel_ru',
        ),
        migrations.RemoveField(
            model_name='books',
            name='yazyk_ky',
        ),
        migrations.RemoveField(
            model_name='books',
            name='yazyk_ru',
        ),
        migrations.RemoveField(
            model_name='order',
            name='region',
        ),
        migrations.AddField(
            model_name='store',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KG'),
        ),
        migrations.AddField(
            model_name='store',
            name='social_network',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='v_nalich',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('БИШКЕК', 'БИШКЕК'), ('ОШ', 'ОШ')], max_length=9, null=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
