# Generated by Django 6.0.2 on 2026-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0002_fix_reklama_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pereplet_ky',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Переплет'),
        ),
        migrations.AddField(
            model_name='books',
            name='pereplet_ru',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pereplet',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='books',
            name='v_nalich',
            field=models.CharField(blank=True, choices=[('БИШКЕК', 'БИШКЕК'), ('ОШ', 'ОШ'), ('Бишкек,Oш', 'Бишкек,Oш'), ('В наличи нет', 'В наличи нет')], max_length=26, null=True, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ky',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
