# Generated by Django 6.0.2 on 2026-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0003_books_pereplet_ky_books_pereplet_ru_and_more'),
    ]

    operations = [
    ]
