# Generated by Django 6.0.2 on 2026-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0003_remove_books_artikul_ky_remove_books_artikul_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
