# Generated by Django 6.0.2 on 2026-04-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0004_add_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pereplet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pereplet_ky',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pereplet_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Переплет'),
        ),
        migrations.AlterField(
            model_name='books',
            name='v_nalich',
            field=models.CharField(blank=True, choices=[('Бишкекте гана', 'Бишкекте гана'), ('Ошто гана', 'Ошто гана'), ('Ошто жана Бишкекте', 'Ошто жана Бишкекте'), ('Сатууда жок', 'Сатууда жок')], max_length=40, null=True, verbose_name='Наличие'),
        ),
    ]
