# Generated by Django 6.0.2 on 2026-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0004_books_description_alter_sale_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='v_nalich',
            field=models.CharField(blank=True, choices=[('БИШКЕК', 'БИШКЕК'), ('ОШ', 'ОШ'), ('Бишкек,Oш', 'Бишкек,Oш')], max_length=26, null=True, verbose_name='Наличие'),
        ),
    ]
