# Generated by Django 6.0.2 on 2026-04-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0005_alter_books_price_alter_books_v_nalich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='baalu.books'),
        ),
    ]
