# Generated by Django 6.0.2 on 2026-04-11 18:24
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0006_alter_orderitem_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_region_ky',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_region_ru',
        ),
        migrations.AddField(
            model_name='books',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
