# Generated by Django 6.0.2 on 2026-04-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0007_remove_store_store_region_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='books',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
    ]
