# Generated by Django 6.0.2 on 2026-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0008_alter_books_options_books_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='artikul',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул'),
        ),
    ]
