# Generated by Django 6.0.2 on 2026-04-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0009_alter_books_artikul'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='books_reklama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reklama', to='baalu.books'),
            preserve_default=False,
        ),
    ]
