# Generated by Django 6.0.2 on 2026-04-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0010_reklama_books_reklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='books_reklama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reklama', to='baalu.books'),
        ),
    ]
