# Generated by Django 6.0.2 on 2026-04-16 19:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0010_reklama_books_reklama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='reklama',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='reklama',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='books',
            name='age_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='qr_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='books_reklama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reklama', to='baalu.books'),
        ),
    ]
