# Generated by Django 6.0.2 on 2026-04-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0011_alter_category_options_alter_reklama_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='artikul',
        ),
        migrations.RemoveField(
            model_name='books',
            name='tirazh',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_icon',
        ),
        migrations.CreateModel(
            name='FinikPostPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=500, verbose_name='ID платежа в Finik')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешный платёж'), ('FAILED', 'Ошибка оплаты'), ('CANCELLED', 'Отменён'), ('PENDING', 'В обработке')], max_length=50, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('raw_data', models.JSONField(verbose_name='Сырой ответ от Finik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paying_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finik_post_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платёж после оплаты',
                'verbose_name_plural': 'Платёж после оплаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinikPrePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('REDIRECTED', 'Переход к оплате'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='CREATED', max_length=20, verbose_name='Статус')),
                ('provider_order_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='ID заказа в Finik')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ от Finik')),
                ('payment_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на оплату')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_payment', to='baalu.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finik_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж перед оплатой',
                'verbose_name_plural': 'Платёж перед оплатой',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
