# Generated by Django 6.0.2 on 2026-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0012_alter_category_options_alter_reklama_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='qr_url',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
