# Generated by Django 6.0.2 on 2026-04-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0011_alter_category_options_alter_reklama_options_and_more'),
        ('baalu', '0013_alter_payment_qr_url'),
    ]

    operations = [
    ]
