# Generated by Django 6.0.2 on 2026-04-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baalu', '0014_merge_20260417_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='artikul',
        ),
        migrations.RemoveField(
            model_name='books',
            name='tirazh',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_icon',
        ),
    ]
